/**
 * Photo library for listing and hero imagery.
 *
 * Every photo is CC0 1.0 (public domain dedication), discovered through the
 * Openverse API and committed to `public/photos` so the demo never depends on
 * a third-party CDN staying up. CC0 waives the attribution requirement; we
 * credit anyway — see `/credits`, linked from the footer.
 *
 * GENERATED by scripts/build-photos.mjs — edit that script, not this file.
 */

export interface Photo {
  src: string;
  width: number;
  height: number;
  /** 16px inline WebP, used as next/image's blur placeholder. */
  blurDataURL: string;
  /** Title as published by the source, used as the credit line label. */
  title: string | null;
  /** Null for sources that publish without a named photographer. */
  creator: string | null;
  creatorUrl: string | null;
  source: string;
  sourceUrl: string;
  license: string;
  licenseUrl: string;
}

export const PHOTOS: Record<string, Photo> = {
  "hero": {
    src: "/photos/hero.webp",
    width: 1300,
    height: 867,
    blurDataURL: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAsAA4BaJZQCsADHXr4hF1CAAP7vjYkm7I63pK2C6lv580uwZwD3WpVTH0YeG9AM1sDQ5h1T1ki3kNfPe7f1JL2y1JYIDiiojjRLlAA=",
    title: "Crowd shopping street, tourists. View",
    creator: null,
    creatorUrl: null,
    source: "Rawpixel",
    sourceUrl: "https://www.rawpixel.com/image/8809318/photo-image-light-people-public-domain",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "cafe-1": {
    src: "/photos/cafe-1.webp",
    width: 1024,
    height: 678,
    blurDataURL: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAsAA4BaJZQAAfaFgIEAAP7UxHOk0maLWTIfTveIuKqic1qUpXk/RZCCWV6rYgo1THe/UDUIVsU0FoSQ/uAgi+76Ecj9poBVFYuAAAA=",
    title: "Tables cushions cafe interior Istanbul",
    creator: null,
    creatorUrl: null,
    source: "Rawpixel",
    sourceUrl: "https://www.rawpixel.com/image/3303531/free-photo-image-zoom-background-cafe-beverage",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "cafe-2": {
    src: "/photos/cafe-2.webp",
    width: 960,
    height: 640,
    blurDataURL: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAsAA4BaJaACdAEf2rTU+IAA/vGzOp0hkh3BQoFP/9nV5361VqtkywEerb+dX8plhTfBog6U4/N91NpLOs807Civ00WTIkMd3geWlzCAAA==",
    title: "Coffee Latte",
    creator: "Nolan Issac",
    creatorUrl: "https://stocksnap.io/author/13560",
    source: "StockSnap",
    sourceUrl: "https://stocksnap.io/photo/coffee-latte-RP0EJV51J6",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "restaurant": {
    src: "/photos/restaurant.webp",
    width: 1440,
    height: 1080,
    blurDataURL: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQAgCdASoQAAwAA4BaJQBOgMYilePSwiNgAP6HqI+9UJrjUSvZ1RpCikbYrn+wHoRzeZ4HYBPzdir7VoIU3vzjyaIDlKBFcA8NogJF/E63tv50QW7m46rtdgX1ZnYIwbqas4gkAAA=",
    title: "Vimala's Curryblossom Cafe - interior",
    creator: "Mx. Granger",
    creatorUrl: "https://commons.wikimedia.org/wiki/User:Mx._Granger",
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=80191035",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
  },
  "bakery": {
    src: "/photos/bakery.webp",
    width: 1440,
    height: 1080,
    blurDataURL: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAwAA4BaJbACdAEOfuHLgAD9UWJeWpvhhp0lqS5H2POUQ+0Wpi72WqDNGoQFBprO765/VFFdvuE7K2T7160t51o90c/mkAAAAA==",
    title: "HK 紅磡 Hung Hom 紅聯道 Hung Luen Road 嘉利酒店 Kerry Hotel shop 大灣咖啡廳 Big Bay Cafe Restaurant buffet bakery breads n cakes May 2026 R12S 05",
    creator: "WMboeOO PPYEE",
    creatorUrl: "https://commons.wikimedia.org/wiki/User:WMboeOO_PPYEE",
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=191726731",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
  },
  "bikeshop-1": {
    src: "/photos/bikeshop-1.webp",
    width: 1440,
    height: 1080,
    blurDataURL: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAwAA4BaJQBdgB6RVFZwAAD5byJq/YLvXdeRbTV7/ECYYwcK2d0kXnnBhEtjhV+5mZXXbIbZbrU1u2tnTs6tmGGpfDW2/mZUwm97CAAAAA==",
    title: "Bicycle shop MATE in Ebisu",
    creator: "Syced",
    creatorUrl: "https://commons.wikimedia.org/wiki/User:Syced",
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=114433500",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
  },
  "bikeshop-2": {
    src: "/photos/bikeshop-2.webp",
    width: 1440,
    height: 1080,
    blurDataURL: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABQAgCdASoQAAwAA4BaJZQC7AEVvPnnDOlOjgAA/u7zke3vI1uiSm3Nap2q0H06d93YZi39kcc/aNu9ed3+qsXTbVEmmSi43rLpvHAANTAAAA==",
    title: "Bicycles shop in Ebisu",
    creator: "Syced",
    creatorUrl: "https://commons.wikimedia.org/wiki/User:Syced",
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=115333737",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
  },
  "store-1": {
    src: "/photos/store-1.webp",
    width: 1440,
    height: 960,
    blurDataURL: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAsAA4BaJYgCdAEWZS+RrXdAAPacF3QzNQmuU2EHeQUlhhdeZI3zwovvCKrldvYxXGhypeZn7VB/rntyqdpp9NLju86LYs+2ATvlS4c3DpgmPRpkTfR3gAA=",
    title: "Dominick DiBartolomeo at The Cheese Store of Beverly Hills (2023)",
    creator: "CaliEditor76",
    creatorUrl: "https://commons.wikimedia.org/w/index.php?title=User:CaliEditor76&action=edit&redlink=1",
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=163600668",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
  },
  "store-2": {
    src: "/photos/store-2.webp",
    width: 1440,
    height: 1080,
    blurDataURL: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAwAA4BaJaACdAEfxH2pYP0AAP5fZeEGyNmoYKyb1QyjI8BbGyPTMACHVX/pHAVDdi81IH4FgSU27QK22BrsnGpJIduahZtQ5pmniEyBgAAA",
    title: "Elgin General Store Front",
    creator: "Johyuznemanohy",
    creatorUrl: "https://commons.wikimedia.org/w/index.php?title=User:Johyuznemanohy&action=edit&redlink=1",
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=191446494",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
  },
  "bookstore": {
    src: "/photos/bookstore.webp",
    width: 1024,
    height: 768,
    blurDataURL: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAwAA4BaJQBOgB0+L5/g2IAA/IxQHATfpqM4nA+aPup5sNQn7nd5nC+9AMgk2gdlG1k947eu9bobArtTFhQZCxh1wvT1VbJtcXqji2QwAA==",
    title: "Free library shelves many books",
    creator: null,
    creatorUrl: null,
    source: "Rawpixel",
    sourceUrl: "https://www.rawpixel.com/image/5912044/image-book-public-domain-room",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "florist-1": {
    src: "/photos/florist-1.webp",
    width: 960,
    height: 631,
    blurDataURL: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQAgCdASoQAAsAA4BaJagCdAYvYAAchk3QLAAA/tmYkvBuk4ntAXKAk2nnuCxP8kvjtgxtbqOZgfd8qz6feyVE8w+XUF6sM196N4nSk/gI51Yt+zwZ2F0BHjliL72IAAA=",
    title: "Flower Shop",
    creator: "Studio 7042",
    creatorUrl: "https://twitter.com/studio7042",
    source: "StockSnap",
    sourceUrl: "https://stocksnap.io/photo/flower-shop-IV7EK6TSJS",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "florist-2": {
    src: "/photos/florist-2.webp",
    width: 960,
    height: 640,
    blurDataURL: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwAgCdASoQAAsAA4BaJagCdAYsj2zMKk8z4AD9/FD5QFEj0lUmXNGsJspeWaz5IuBMHMrkqVhhFaFsv5L6dDa2hsHlQcNoeAqYU2yNQL9y6X3ymvGu2qSLS294gj0ehvaQqg/YAAA=",
    title: "Flower Shop",
    creator: "Bruce Mars",
    creatorUrl: "https://stocksnap.io/author/brucemars",
    source: "StockSnap",
    sourceUrl: "https://stocksnap.io/photo/flower-shop-WNQMLAIYXP",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "laundromat-1": {
    src: "/photos/laundromat-1.webp",
    width: 960,
    height: 640,
    blurDataURL: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAQCdASoQAAsAA4BaJaQAD5Jl6BAAAP7I9qJdbcrZLeVWhewM81ghkdD5ZN2PI+uohFJRv4qFNsWxTzHSeJzIgxpOwEUoFqs4O6c+MxgAAA==",
    title: "Laundry Laundromat",
    creator: "Ryan McGuire",
    creatorUrl: "https://www.gratisography.com",
    source: "StockSnap",
    sourceUrl: "https://stocksnap.io/photo/laundry-laundromat-4876CF9B9C",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "laundromat-2": {
    src: "/photos/laundromat-2.webp",
    width: 1440,
    height: 1080,
    blurDataURL: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQAgCdASoQAAwAA4BaJZQCdAYt9lMxPCljoYAA+/XyFC2+sf43cpRcn/cUHHB4eZ7efTtYGlFn2bx6+VjGxRQVg0H5dUqW5gmE6X5NMMaKLIpG/zJHVyWBz9EOQAAA",
    title: "Handa Laundry World 2022-03-13",
    creator: "Asanagi",
    creatorUrl: "https://commons.wikimedia.org/wiki/User:Asanagi",
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=116730672",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
  },
  "cleaning": {
    src: "/photos/cleaning.webp",
    width: 1024,
    height: 680,
    blurDataURL: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAsAA4BaJYwCdAEWYAfia0L4AMyUAboEG2ZE7ruk2unKJglIYN1PRaiKJC3hmqY9Yo70+kFL/pAWRAQyb9ZoSbq0EWxgAAA=",
    title: "Free skyscraper window cleaning services",
    creator: null,
    creatorUrl: null,
    source: "Rawpixel",
    sourceUrl: "https://www.rawpixel.com/image/5906435/photo-image-public-domain-blue-people",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "barber-1": {
    src: "/photos/barber-1.webp",
    width: 1024,
    height: 679,
    blurDataURL: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQAgCdASoQAAsAA4BaJYgCdAYtzwRq+iYkNoAA/u0tKfdQEZgybte3UVuKo7w1yf2PC0ff8xiK8z4bqXYThs7fUFN6e62nEw9mQJkjTgq8rN2MAPDSzFRuDUfF4N1H0NIdTNf21BrtAAAA",
    title: "Old barber shop",
    creator: null,
    creatorUrl: null,
    source: "Rawpixel",
    sourceUrl: "https://www.rawpixel.com/image/5939531/old-barber-shop",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "barber-2": {
    src: "/photos/barber-2.webp",
    width: 1440,
    height: 810,
    blurDataURL: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJQBOj+AB1Bk3kwAAzIkRGzidDJR4RHDPWUwFriqOlKWkKAdVE+LUlevfA3CoggyenRxvr4oeqaCL/C5zyozIF7spAAAA",
    title: "Hair salon - Arlington, MA",
    creator: "Daderot",
    creatorUrl: "https://commons.wikimedia.org/wiki/User:Daderot",
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=152759009",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
  },
  "office-1": {
    src: "/photos/office-1.webp",
    width: 960,
    height: 640,
    blurDataURL: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAsAA4BaJZwAAtutnaXRtoAA/mbe74GirjpLws4cQ6dyvAAhqa4OqWLT/3mwqPdYnGsJQe4pMulLtF0V9lA4OkPEJAFQIAA=",
    title: "Home Office",
    creator: "Design by Matt",
    creatorUrl: "https://mattbango.com",
    source: "StockSnap",
    sourceUrl: "https://stocksnap.io/photo/home-office-QUU0AQABSN",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "office-2": {
    src: "/photos/office-2.webp",
    width: 1024,
    height: 683,
    blurDataURL: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAQCdASoQAAsAA4BaJYwC7ADW2/QHAADN5ZWGglb3SNVvt4KAvs0djYMiXVf3gMN6VARHmc0OLOcTwmX83KZpljkn7TGk59gD8kHO/iwIEwWrC+83raHE93As3t/P1cEAAA==",
    title: "Modern office, green workplace",
    creator: "usembassynewzealand",
    creatorUrl: null,
    source: "Rawpixel",
    sourceUrl: "https://www.rawpixel.com/image/8752669/photo-image-public-domain-table-office",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "studio": {
    src: "/photos/studio.webp",
    width: 960,
    height: 720,
    blurDataURL: "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAwAA4BaJbACdAEfkFYOazUAAPyO7HGKOkKgkBSIn7by0csstPNauxl7U5GfhGD3+Vlw6yftkYrj9w9FjzaCY1xLhBMFWDqEV2hrIIyQKUUik3A21iflJmIDAAAA",
    title: "Office Work",
    creator: "Jeffrey Betts",
    creatorUrl: "http://mmtstock.com",
    source: "StockSnap",
    sourceUrl: "https://stocksnap.io/photo/office-work-91WZ32J28K",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "datacenter-1": {
    src: "/photos/datacenter-1.webp",
    width: 1024,
    height: 576,
    blurDataURL: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJbACdAEfkdCiYAAA/uyOdLPBB/afH7dHyO+Xy8QDQJkmcrkzKStEAH1xzP/Fq9fPqT+/VPj5OXBPJWqDLyzSoAA=",
    title: "Free computer server room image",
    creator: null,
    creatorUrl: null,
    source: "Rawpixel",
    sourceUrl: "https://www.rawpixel.com/image/5906639/photo-image-light-desktop-wallpapers-public-domain",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "datacenter-2": {
    src: "/photos/datacenter-2.webp",
    width: 960,
    height: 640,
    blurDataURL: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAsAA4BaJaACdADJM/CFMAAA/okP+VzhZjrUZaxj4WElOW3baQ0keNWHZix/F2GeqT7uLzMRIW2DCy6seAOIe77h/vqAAAA=",
    title: "Office Work",
    creator: "Negative Space",
    creatorUrl: "https://stocksnap.io/author/4440",
    source: "StockSnap",
    sourceUrl: "https://stocksnap.io/photo/office-work-8P6GFHP0LU",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "watersports-1": {
    src: "/photos/watersports-1.webp",
    width: 960,
    height: 640,
    blurDataURL: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABwAgCdASoQAAsAA4BaJbACdAYtpgLPOr1yAR4AAP6g11NaXgsZXrWjIBaB/POzQl2hGyYO3aoWFWDZg6zsqoXntoG7v44E7w9h+E11cH2wvBwYaT7X8aoO5S7dDQQ8AGOEPLYeLrejI6qmPxpeZ40AAAA=",
    title: "Kayaking Boat",
    creator: "Kristin Hardwick",
    creatorUrl: "https://www.kristinhardwick.com",
    source: "StockSnap",
    sourceUrl: "https://stocksnap.io/photo/kayaking-boat-N3TUF32ALJ",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "watersports-2": {
    src: "/photos/watersports-2.webp",
    width: 960,
    height: 640,
    blurDataURL: "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoQAAsAA4BaJQBOgCHWrsQAAP7u8tAaAQbDT7mCj+V4vXbFuwZEUc18PHzFxWdXpPjmq0f20eqAAA==",
    title: "Kayak Lake",
    creator: "Patrick Fore",
    creatorUrl: "https://stocksnap.io/author/7557",
    source: "StockSnap",
    sourceUrl: "https://stocksnap.io/photo/kayak-lake-DTHNKC77UG",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "gym-1": {
    src: "/photos/gym-1.webp",
    width: 960,
    height: 640,
    blurDataURL: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAsAA4BaJYwAD4tQdNZDAiiqIAD+7Vnf/0MDTXOckerhp5CqL38xJ30zVD9JJqExQhku6iC5bb0fKPptUoNryNbOINhV2bKA+I2ubKwg7zz0C0c/ve8p/PToAA==",
    title: "Gym Interior",
    creator: "Humphrey Muleba",
    creatorUrl: "https://burst.shopify.com/@goodcitizen",
    source: "StockSnap",
    sourceUrl: "https://stocksnap.io/photo/gym-interior-LNCLN1NE6K",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "gym-2": {
    src: "/photos/gym-2.webp",
    width: 960,
    height: 540,
    blurDataURL: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAkAA4BaJYgCdAYrxtb9w0EAAP5O6InRmOOJPPwaG+zdTN6KjH1rwkCw+T6APi+VBdx1XU2FS4WPgSWrLdmPhh6kVQ98wRwOajBlm0MtJeCYbLwAAA==",
    title: "Girl Gym",
    creator: "Khusen Rustamov",
    creatorUrl: "https://stocksnap.io/author/34661",
    source: "StockSnap",
    sourceUrl: "https://stocksnap.io/photo/girl-gym-00RNNUWGLM",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
};

/** Full-bleed photo behind the browse hero. */
export const HERO_PHOTO = PHOTOS["hero"];

/** Every credited photo, for the /credits page. */
export const ALL_PHOTOS: Photo[] = Object.values(PHOTOS);

type Topic = "cafe" | "restaurant" | "bakery" | "bikeshop" | "store" | "bookstore" | "florist" | "laundromat" | "cleaning" | "barber" | "office" | "studio" | "datacenter" | "watersports" | "gym";

/** Photos available for each business topic. */
const TOPIC_PHOTOS: Record<Topic, string[]> = {
  cafe: ["cafe-1", "cafe-2"],
  restaurant: ["restaurant"],
  bakery: ["bakery"],
  bikeshop: ["bikeshop-1", "bikeshop-2"],
  store: ["store-1", "store-2"],
  bookstore: ["bookstore"],
  florist: ["florist-1", "florist-2"],
  laundromat: ["laundromat-1", "laundromat-2"],
  cleaning: ["cleaning"],
  barber: ["barber-1", "barber-2"],
  office: ["office-1", "office-2"],
  studio: ["studio"],
  datacenter: ["datacenter-1", "datacenter-2"],
  watersports: ["watersports-1", "watersports-2"],
  gym: ["gym-1", "gym-2"],
};

/**
 * Title keywords mapped to a topic, most specific first. A listing's own name
 * is a far better photo cue than its industry — "Harbor Street Laundromat" and
 * "Ledger Lane Bookkeeping" are both `services` but should not share a photo.
 */
const TITLE_TOPICS: [RegExp, Topic][] = [
  [/bakery|baker|bread|patisserie|crumb|pastry/i, "bakery"],
  [/caf[e\u00e9]|coffee|espresso|kettle|roast|brew|tea\b/i, "cafe"],
  [/restaurant|bistro|grill|kitchen|deli|table|taco|pizza|noodle|saffron/i, "restaurant"],
  [/bike|bicycle|cycle|pedal|wheel/i, "bikeshop"],
  [/book|read|library|novel|page/i, "bookstore"],
  [/flower|floral|florist|bloom|stem|petal|garden/i, "florist"],
  [/laundr|launderette|washer|dry clean/i, "laundromat"],
  [/clean|janitor|maid|sparkle|shine|bright/i, "cleaning"],
  [/barber|salon|hair|groom|spa|nail|beauty/i, "barber"],
  [/bookkeep|account|ledger|tax|payroll|legal|consult|insur|advis|agency/i, "office"],
  [/studio|design|creative|pixel|brand|media|print|craft|pottery/i, "studio"],
  [/data|backup|cloud|host|server|network|managed|software|\bit\b|tech|cyber/i, "datacenter"],
  [/board|kayak|paddle|surf|marine|dive|boat|rental|beach/i, "watersports"],
  [/fitness|gym|yoga|pilates|crossfit|strength|athletic|iron|club/i, "gym"],
  [/pet|supply|store|shop|market|grocer|boutique|outfit|goods|mercantile/i, "store"],
];

/** Topics to draw on when a listing's title matches nothing specific. */
const INDUSTRY_TOPICS: Record<string, Topic[]> = {
  food: ["cafe", "restaurant", "bakery"],
  retail: ["store", "bikeshop", "bookstore", "florist"],
  services: ["barber", "laundromat", "cleaning", "office"],
  tech: ["studio", "office", "datacenter"],
  others: ["gym", "watersports"],
};

const FALLBACK_TOPICS: Topic[] = ["store", "cafe", "office"];

/** Stable non-negative hash, so a listing keeps the same photos across renders. */
function hash(seed: string) {
  let h = 0;
  for (let i = 0; i < seed.length; i++) {
    h = seed.charCodeAt(i) + ((h << 5) - h);
    h |= 0;
  }
  return Math.abs(h);
}

function topicsFor(title: string, industry: string): Topic[] {
  const matched = TITLE_TOPICS.find(([pattern]) => pattern.test(title))?.[1];
  const industryTopics =
    INDUSTRY_TOPICS[industry?.toLowerCase()] ?? FALLBACK_TOPICS;
  // Matched topic leads; the industry pool (then everything) backs it up so
  // the detail page always has enough distinct photos for its mosaic.
  return [
    ...(matched ? [matched] : []),
    ...industryTopics,
    ...(Object.keys(TOPIC_PHOTOS) as Topic[]),
  ];
}

/**
 * Resolve photos for one listing, best match first. Always returns up to
 * `count` distinct photos, rotated by listing id so two coffee shops don't
 * show the same picture.
 */
export function photosForListing(
  { _id, title, industry }: { _id: string; title: string; industry: string },
  count = 3,
): Photo[] {
  const seen = new Set<string>();
  const slugs: string[] = [];
  const offset = hash(_id ?? "");

  for (const topic of topicsFor(title ?? "", industry ?? "")) {
    const pool = TOPIC_PHOTOS[topic] ?? [];
    for (let i = 0; i < pool.length; i++) {
      const slug = pool[(offset + i) % pool.length];
      if (seen.has(slug)) continue;
      seen.add(slug);
      slugs.push(slug);
    }
    if (slugs.length >= count) break;
  }

  return slugs.slice(0, count).map((slug) => PHOTOS[slug]);
}

/** The single photo used for a listing's card and row thumbnail. */
export function photoForListing(listing: {
  _id: string;
  title: string;
  industry: string;
}): Photo {
  return photosForListing(listing, 1)[0];
}
