#!/usr/bin/env node
/**
 * Rebuild `public/photos/*.webp` and `lib/photos.ts` from
 * `scripts/photo-sources.json`.
 *
 * The photos are CC0 1.0 images discovered through the Openverse API
 * (https://api.openverse.org). `photo-sources.json` is the durable record of
 * what was chosen: the remote URL, the licence, and the credit fields. Running
 * this script re-downloads each one, re-encodes it to a width-capped WebP, and
 * regenerates the typed manifest that the app imports.
 *
 * Committing the encoded images means the demo never breaks because an
 * upstream CDN moved a file — this script exists so the choice is auditable
 * and repeatable, not because the build depends on the network.
 *
 *   node scripts/build-photos.mjs            # skip images already on disk
 *   node scripts/build-photos.mjs --force    # re-download everything
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..");
const SOURCES = path.join(HERE, "photo-sources.json");
const OUT_DIR = path.join(ROOT, "public", "photos");
const OUT_MODULE = path.join(ROOT, "lib", "photos.ts");

const MAX_WIDTH = 1440;
const WEBP_QUALITY = 78;
const FORCE = process.argv.includes("--force");

// Wikimedia's user-agent policy requires a descriptive agent with contact
// details; anonymous requests get 429ed. The same agent is fine for the other
// hosts, so use it for every download.
const HEADERS = {
  "User-Agent":
    "ScoutboardPortfolioDemo/1.0 (https://github.com/Jadesuuu/scoutboard) node-fetch",
  Accept: "image/jpeg,image/png,image/webp,image/*,*/*",
};

const SOURCE_LABELS = {
  rawpixel: "Rawpixel",
  stocksnap: "StockSnap",
  wikimedia: "Wikimedia Commons",
};
const LICENSE_LABELS = { cc0: "CC0 1.0" };

/** Topics the app can match a listing to, in the order they appear in the file. */
function groupTopics(records) {
  const topics = [];
  for (const r of records) {
    if (r.topic === "hero") continue;
    if (!topics.includes(r.topic)) topics.push(r.topic);
  }
  return topics;
}

/**
 * A 16px-wide WebP as a data URI, used as next/image's blur placeholder.
 * Costs a few hundred bytes each and removes the grey-box flash while the
 * real photo streams in.
 */
async function blurPlaceholder(file) {
  const buf = await sharp(file)
    .resize(16, null, { fit: "inside" })
    .webp({ quality: 40 })
    .toBuffer();
  return `data:image/webp;base64,${buf.toString("base64")}`;
}

async function download(record) {
  const file = path.join(OUT_DIR, `${record.slug}.webp`);
  if (!FORCE && fs.existsSync(file)) {
    const meta = await sharp(file).metadata();
    return {
      file,
      width: meta.width,
      height: meta.height,
      blurDataURL: await blurPlaceholder(file),
      cached: true,
    };
  }

  const res = await fetch(record.remoteUrl, {
    headers: HEADERS,
    redirect: "follow",
  });
  if (!res.ok) {
    throw new Error(`HTTP ${res.status} for ${record.remoteUrl}`);
  }

  const buf = Buffer.from(await res.arrayBuffer());
  await sharp(buf)
    .rotate() // honour EXIF orientation before we discard the metadata
    .resize(MAX_WIDTH, null, { withoutEnlargement: true })
    .webp({ quality: WEBP_QUALITY })
    .toFile(file);

  const meta = await sharp(file).metadata();
  return {
    file,
    width: meta.width,
    height: meta.height,
    blurDataURL: await blurPlaceholder(file),
    cached: false,
  };
}

const json = (v) => (v === null || v === undefined ? "null" : JSON.stringify(v));

function renderModule(records, topics) {
  const entries = records
    .map(
      (p) => `  ${JSON.stringify(p.slug)}: {
    src: ${json(p.src)},
    width: ${p.width},
    height: ${p.height},
    blurDataURL: ${json(p.blurDataURL)},
    title: ${json(p.title)},
    creator: ${json(p.creator)},
    creatorUrl: ${json(p.creatorUrl)},
    source: ${json(SOURCE_LABELS[p.source] ?? p.source)},
    sourceUrl: ${json(p.sourceUrl)},
    license: ${json(LICENSE_LABELS[p.license] ?? p.license)},
    licenseUrl: ${json(p.licenseUrl)},
  },`,
    )
    .join("\n");

  const sets = topics
    .map(
      (t) =>
        `  ${t}: [${records
          .filter((p) => p.topic === t)
          .map((p) => JSON.stringify(p.slug))
          .join(", ")}],`,
    )
    .join("\n");

  return `/**
 * Photo library for listing and hero imagery.
 *
 * Every photo is CC0 1.0 (public domain dedication), discovered through the
 * Openverse API and committed to \`public/photos\` so the demo never depends on
 * a third-party CDN staying up. CC0 waives the attribution requirement; we
 * credit anyway — see \`/credits\`, linked from the footer.
 *
 * GENERATED by scripts/build-photos.mjs — edit that script, not this file.
 */

export interface Photo {
  src: string;
  width: number;
  height: number;
  /** 16px inline WebP, used as next/image's blur placeholder. */
  blurDataURL: string;
  /** Title as published by the source, used as the credit line label. */
  title: string | null;
  /** Null for sources that publish without a named photographer. */
  creator: string | null;
  creatorUrl: string | null;
  source: string;
  sourceUrl: string;
  license: string;
  licenseUrl: string;
}

export const PHOTOS: Record<string, Photo> = {
${entries}
};

/** Full-bleed photo behind the browse hero. */
export const HERO_PHOTO = PHOTOS["hero"];

/** Every credited photo, for the /credits page. */
export const ALL_PHOTOS: Photo[] = Object.values(PHOTOS);

type Topic = ${topics.map((t) => JSON.stringify(t)).join(" | ")};

/** Photos available for each business topic. */
const TOPIC_PHOTOS: Record<Topic, string[]> = {
${sets}
};

/**
 * Title keywords mapped to a topic, most specific first. A listing's own name
 * is a far better photo cue than its industry — "Harbor Street Laundromat" and
 * "Ledger Lane Bookkeeping" are both \`services\` but should not share a photo.
 */
const TITLE_TOPICS: [RegExp, Topic][] = [
  [/bakery|baker|bread|patisserie|crumb|pastry/i, "bakery"],
  [/caf[e\\u00e9]|coffee|espresso|kettle|roast|brew|tea\\b/i, "cafe"],
  [/restaurant|bistro|grill|kitchen|deli|table|taco|pizza|noodle|saffron/i, "restaurant"],
  [/bike|bicycle|cycle|pedal|wheel/i, "bikeshop"],
  [/book|read|library|novel|page/i, "bookstore"],
  [/flower|floral|florist|bloom|stem|petal|garden/i, "florist"],
  [/laundr|launderette|washer|dry clean/i, "laundromat"],
  [/clean|janitor|maid|sparkle|shine|bright/i, "cleaning"],
  [/barber|salon|hair|groom|spa|nail|beauty/i, "barber"],
  [/bookkeep|account|ledger|tax|payroll|legal|consult|insur|advis|agency/i, "office"],
  [/studio|design|creative|pixel|brand|media|print|craft|pottery/i, "studio"],
  [/data|backup|cloud|host|server|network|managed|software|\\bit\\b|tech|cyber/i, "datacenter"],
  [/board|kayak|paddle|surf|marine|dive|boat|rental|beach/i, "watersports"],
  [/fitness|gym|yoga|pilates|crossfit|strength|athletic|iron|club/i, "gym"],
  [/pet|supply|store|shop|market|grocer|boutique|outfit|goods|mercantile/i, "store"],
];

/** Topics to draw on when a listing's title matches nothing specific. */
const INDUSTRY_TOPICS: Record<string, Topic[]> = {
  food: ["cafe", "restaurant", "bakery"],
  retail: ["store", "bikeshop", "bookstore", "florist"],
  services: ["barber", "laundromat", "cleaning", "office"],
  tech: ["studio", "office", "datacenter"],
  others: ["gym", "watersports"],
};

const FALLBACK_TOPICS: Topic[] = ["store", "cafe", "office"];

/** Stable non-negative hash, so a listing keeps the same photos across renders. */
function hash(seed: string) {
  let h = 0;
  for (let i = 0; i < seed.length; i++) {
    h = seed.charCodeAt(i) + ((h << 5) - h);
    h |= 0;
  }
  return Math.abs(h);
}

function topicsFor(title: string, industry: string): Topic[] {
  const matched = TITLE_TOPICS.find(([pattern]) => pattern.test(title))?.[1];
  const industryTopics =
    INDUSTRY_TOPICS[industry?.toLowerCase()] ?? FALLBACK_TOPICS;
  // Matched topic leads; the industry pool (then everything) backs it up so
  // the detail page always has enough distinct photos for its mosaic.
  return [
    ...(matched ? [matched] : []),
    ...industryTopics,
    ...(Object.keys(TOPIC_PHOTOS) as Topic[]),
  ];
}

/**
 * Resolve photos for one listing, best match first. Always returns up to
 * \`count\` distinct photos, rotated by listing id so two coffee shops don't
 * show the same picture.
 */
export function photosForListing(
  { _id, title, industry }: { _id: string; title: string; industry: string },
  count = 3,
): Photo[] {
  const seen = new Set<string>();
  const slugs: string[] = [];
  const offset = hash(_id ?? "");

  for (const topic of topicsFor(title ?? "", industry ?? "")) {
    const pool = TOPIC_PHOTOS[topic] ?? [];
    for (let i = 0; i < pool.length; i++) {
      const slug = pool[(offset + i) % pool.length];
      if (seen.has(slug)) continue;
      seen.add(slug);
      slugs.push(slug);
    }
    if (slugs.length >= count) break;
  }

  return slugs.slice(0, count).map((slug) => PHOTOS[slug]);
}

/** The single photo used for a listing's card and row thumbnail. */
export function photoForListing(listing: {
  _id: string;
  title: string;
  industry: string;
}): Photo {
  return photosForListing(listing, 1)[0];
}
`;
}

async function main() {
  const records = JSON.parse(fs.readFileSync(SOURCES, "utf8"));
  fs.mkdirSync(OUT_DIR, { recursive: true });

  let bytes = 0;
  let fetched = 0;
  for (const record of records) {
    const { file, width, height, blurDataURL, cached } = await download(record);
    record.width = width;
    record.height = height;
    record.blurDataURL = blurDataURL;
    bytes += fs.statSync(file).size;
    if (!cached) {
      fetched += 1;
      // Be a polite client when walking the whole list.
      await new Promise((r) => setTimeout(r, 800));
    }
  }

  const topics = groupTopics(records);
  fs.writeFileSync(OUT_MODULE, renderModule(records, topics));
  fs.writeFileSync(SOURCES, JSON.stringify(records, null, 2) + "\n");

  console.log(
    `${records.length} photos (${fetched} downloaded), ${(bytes / 1048576).toFixed(2)} MB`,
  );
  console.log(`wrote ${path.relative(ROOT, OUT_MODULE)}`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
